trigger: none

stages:
- stage: BuildProjects
  displayName: Build and Test projects
  
  pool:
    vmImage: 'macos-latest'

  jobs:
  - job: BuildAndroidProject
    displayName: Build Android Project
    steps:
    - template: templates/restore-build-test.yml
