//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grach.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grach.Core.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string GoIn {
            get {
                return ResourceManager.GetString("GoIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обращаем ваше внимание, что некоторые важные функции приложения будут для вас недоступны..
        /// </summary>
        internal static string LoginOfflineMessage {
            get {
                return ResourceManager.GetString("LoginOfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  наше приложение без авторизации..
        /// </summary>
        internal static string OurAppWithoutAuth {
            get {
                return ResourceManager.GetString("OurAppWithoutAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localized string :).
        /// </summary>
        internal static string ResourceTestString {
            get {
                return ResourceManager.GetString("ResourceTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to протестировать.
        /// </summary>
        internal static string ToTest {
            get {
                return ResourceManager.GetString("ToTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете .
        /// </summary>
        internal static string YouCan {
            get {
                return ResourceManager.GetString("YouCan", resourceCulture);
            }
        }
    }
}
